### ISSUE TITLE
Panic in vim-go when using GoFillStruct

### ISSUE THREAD

**Issue by desdic** [fatih/vim-go#1801]
### What did you do? (required. The issue will be **closed** when not provided.)
Ran GoFillStruct on []rolleInformation{}

### What did you expect to happen?
it would fill out the struct

### What happened instead?
vim-go: panic: interface conversion: ast.Expr is *ast.BasicLit, not *ast.KeyValueExpr                                                                                                                                                                          
vim-go: 
vim-go: goroutine 1 [running]:
vim-go: main.zeroValue(0xc4200976d0, 0xc4221e1620, 0xc427010fc0, 0x68c5e0, 0xc423c1e060, 0x0, 0x1, 0xc42ed5af88, 0x4d8d0a, 0x0)
vim-go:         /home/kgn/go/src/github.com/davidrjenni/reftools/cmd/fillstruct/fill.go:42 +0x259
vim-go: main.byLine.func1(0x68b9a0, 0xc427010fc0, 0xc5d41f2b5a46201)
vim-go:         /home/kgn/go/src/github.com/davidrjenni/reftools/cmd/fillstruct/main.go:269 +0x3ee
vim-go: go/ast.inspector.Visit(0xc4336620c0, 0x68b9a0, 0xc427010fc0, 0x4d8d0a, 0x0)
vim-go:         /usr/lib/go/src/go/ast/walk.go:373 +0x3a
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68b9a0, 0xc427010fc0)
vim-go:         /usr/lib/go/src/go/ast/walk.go:52 +0x66
vim-go: go/ast.walkExprList(0x68b040, 0xc4336620c0, 0xc425af4ee0, 0x1, 0x1)
vim-go:         /usr/lib/go/src/go/ast/walk.go:26 +0x81
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68b9a0, 0xc427011000)
vim-go:         /usr/lib/go/src/go/ast/walk.go:104 +0x42b
vim-go: go/ast.walkExprList(0x68b040, 0xc4336620c0, 0xc425af4f00, 0x1, 0x1)
vim-go:         /usr/lib/go/src/go/ast/walk.go:26 +0x81
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68b620, 0xc427011040)
vim-go:         /usr/lib/go/src/go/ast/walk.go:207 +0x20fa
vim-go: go/ast.walkStmtList(0x68b040, 0xc4336620c0, 0xc4270117c0, 0x3, 0x4)
vim-go:         /usr/lib/go/src/go/ast/walk.go:32 +0x81
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68b7a0, 0xc42de34570)
vim-go:         /usr/lib/go/src/go/ast/walk.go:224 +0x1b61
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68bc20, 0xc42de345d0)
vim-go:         /usr/lib/go/src/go/ast/walk.go:344 +0xd6d
vim-go: go/ast.walkDeclList(0x68b040, 0xc4336620c0, 0xc42bc00600, 0x11, 0x20)
vim-go:         /usr/lib/go/src/go/ast/walk.go:38 +0x81
vim-go: go/ast.Walk(0x68b040, 0xc4336620c0, 0x68bba0, 0xc42dceb780)
vim-go:         /usr/lib/go/src/go/ast/walk.go:353 +0x2650
vim-go: go/ast.Inspect(0x68bba0, 0xc42dceb780, 0xc4336620c0)
vim-go:         /usr/lib/go/src/go/ast/walk.go:385 +0x4b
vim-go: main.byLine(0xc4200a8480, 0xc4200c6180, 0x40, 0x105, 0x68ace0, 0xc4200824d0)
vim-go:         /home/kgn/go/src/github.com/davidrjenni/reftools/cmd/fillstruct/main.go:246 +0x3c9
vim-go: main.main()
vim-go:         /home/kgn/go/src/github.com/davidrjenni/reftools/cmd/fillstruct/main.go:126 +0x339

### Configuration (**MUST** fill this out):

* vim-go version:
1.17

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
set shell=bash

" NeoBundle --- {{{
if has('vim_starting')
  set runtimepath+=~/.config/nvim/bundle/neobundle.vim/
  set runtimepath+=~/.config/nvim/
endif

let neobundle_readme=expand('~/.config/nvim/bundle/neobundle.vim/README.md')

if !filereadable(neobundle_readme)
  echo "Installing NeoBundle..."
  echo ""
  silent !mkdir -p ~/.config/nvim/bundle
  silent !git clone https://github.com/Shougo/neobundle.vim ~/.config/nvim/bundle/neobundle.vim/
  let g:not_finsh_neobundle = "yes"
endif

call neobundle#begin(expand('$HOME/.config/nvim/bundle'))
NeoBundle 'fatih/vim-go.git'
call neobundle#end()
NeoBundleCheck

let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
let g:go_metalinter_autosave = 1
let g:go_fmt_fail_silently = 0
let g:go_fmt_command = "goimports"
let g:go_list_type = "quickfix"
let g:go_auto_type_info = 0
let g:go_def_mode = "guru"
let g:go_echo_command_info = 1
let g:go_gocode_autobuild = 0
let g:go_gocode_unimported_packages = 1
let g:go_autodetect_gopath = 1
let g:go_info_mode = "guru"
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 0
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_structs = 1
let g:go_highlight_space_tab_error = 1
let g:go_highlight_array_whitespace_error = 1
let g:go_highlight_trailing_whitespace_error = 1
let g:go_modifytags_transform = 'camelcase'
let g:go_addtags_transform = 'camelcase'

* Vim version (first three lines from `:version`):
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5

* Go version (`go version`):
go version go1.10.1 linux/amd6

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kgn/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/kgn/go:/home/kgn/src/biq/tingbogen"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build414271976=/tmp/go-build -gno-record-gcc-switches"

**Comment by desdic** [comment]
Sorry .. this should properly be filed under the gofillstruct and not vim-go
