### ISSUE TITLE
GoInfo with gocode appears to hang in Neovim

### ISSUE THREAD

**Issue by berfarah** [fatih/vim-go#1966]
### What did you do? (required. The issue will be **closed** when not provided.)

Minimal config to test:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go'
filetype plugin indent on                   " required!
call plug#end()
```

Opened a file with a definition (any file) and ran `:GoInfo` while on a reference.

In `ps aux | grep gocode`:
```
bernardofarah    40391   0.0  0.1 558473420  24640   ??  S     1:16PM   4:31.00 /path/to/bin/gocode -s -sock unix -addr 127.0.0.1:37373
bernardofarah    31418   0.0  0.1 558472420   8776 s007  S+    1:16PM   0:00.02 /path/to/bin/gocode -sock unix -f vim -builtin autocomplete /path/to/file/db.go 379
bernardofarah    31417   0.0  0.1 558454756   8740 s007  S+    1:16PM   0:00.02 /path/to/bin/gocode -sock unix -f vim -builtin autocomplete /path/to/file/db.go 379
bernardofarah    31408   0.0  0.1 558452964   8724 s007  S+    1:16PM   0:00.02 /path/to/bin/gocode -sock unix -f vim -builtin autocomplete /path/to/file/db.go 281
bernardofarah    31407   0.0  0.1 558453988   8732 s007  S+    1:16PM   0:00.02 /path/to/bin/gocode -sock unix -f vim -builtin autocomplete /path/to/file/db.go 1
```
Each call to `GoInfo` opens a new one of these. I'm running 

### What did you expect to happen?

I expect to get a definition back, even if it's delayed.

### What happened instead?

The command never returns anything. I tried running the same command myself and get the same result. If I cat a file in it seems to work?

### Configuration (**MUST** fill this out):

* vim-go version:

`925447051422b471490a85bcb196a27c4625b225`

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

```
call plug#begin('~/.config/nvim/plugged')
Plug 'fatih/vim-go'
filetype plugin indent on                   " required!
call plug#end()
```

* Vim version (first three lines from `:version`):

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```

* Go version (`go version`):

```
go version go1.10.1 darwin/amd64
```

* Go environment (`go env`):

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bernardofarah/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bernardofarah/dev/go"
GORACE=""
GOROOT="/Users/bernardofarah/dev/opt/go1.10.1"
GOTMPDIR=""
GOTOOLDIR="/Users/bernardofarah/dev/opt/go1.10.1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vj/tblpg3254dzg8z6v8k2lfz380000gp/T/go-build721461437=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

*gocode version*

`github.com/mdempsky/gocode` / `00e7f5ac290aeb20a3d8d31e737ae560a191a1d5`

**Comment by bhcleek** [comment]
I'd recommend use `g:go_info_mode='guru'` or else setting `g:go_gocode_propose_source=1`.

**Comment by bhcleek** [comment]
I'd also recommend that you either take advantage of the statusline integration (https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L1158-L1168) or else ensure that `g:go_echo_command_info` is set to see if the call to gocode is failing or succeeding.

**Comment by bhcleek** [comment]
If you can duplicate it reliably, I'd recommend closing gocode using `gocode exit`, then start it up again using `gocode -s  -debug  -builtin`. After running `:GoInfo`, the output from the gocode server window would be useful to us.

**Comment by berfarah** [comment]
@bhcleek Here's what I've tried:

```
$GOPATH/bin/gocode -s -debug -builtin
```

In a separate window, I open up a go file and run `:GoInfo` on a command. This never hits the server, as I'm still waiting for the command to show up.

When I run other autocompletion (stuff built in with `nvim-completion-manager`) I see debug output.

I've tried the following permutations of the debug command:

```
gocode -s -debug -builtin
gocode -s  -sock unix -builtin -debug
gocode -s -sock unix -addr 127.0.0.1:37373 -debug
```

none of them are responding to the commands that appear to be run:

```
gocode -sock unix -f vim -builtin autocomplete /path/to/main.go 234
```

**Comment by bhcleek** [comment]
At this point, it would probably be most helpful if you could provide a set of files and instructions for what to try to autocomplete while editing one of those files.

**Comment by berfarah** [comment]
@bhcleek Absolutely - thanks for bearing with me! I tried this on my personal machine:

same `vim-go`, `.vimrc` and `gocode` versions but different nvim and go versions, as well as a slightly different environment.

**vim version**
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```

**go version**

```
go version go1.11 darwin/amd64
```

**go env**

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bernardo/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bernardo/dev/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p7/dg16x14n143dmmknqlbzc97h0000gn/T/go-build042182362=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

---

## Steps

1. I used this repository https://github.com/berfarah/knoch
2. I opened `main.go`
3. I put the cursor over `Execute` and ran `:GoInfo`
4. I verified in htop that the command had been dispatched. However, the command appeared not to have reached the server.
5. I repeated step 3.
6. After waiting 5-10 seconds, I closed the editor. At this point, I got a stack trace like the one below (and saw three `vim-go SUCCESS` lines in the stdout):

```
2018/09/13 01:06:45 Got autocompletion request for '/Users/bernardo/dev/golang/src/github.com/berfarah/knoch/main.go'
2018/09/13 01:06:45 Cursor at: 86
panic: runtime error: slice bounds out of range

goroutine 8 [running]:
runtime/debug.Stack(0xb, 0xc000066828, 0x1)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc00000c880)
	/Users/bernardo/dev/golang/src/github.com/mdempsky/gocode/server.go:72 +0x94
panic(0x1453d00, 0x184fd80)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
main.(*Server).AutoComplete(0x187f628, 0xc00014c680, 0xc00000c880, 0x0, 0x0)
	/Users/bernardo/dev/golang/src/github.com/mdempsky/gocode/server.go:84 +0x9d9
reflect.Value.call(0xc0000b64e0, 0xc0000b4578, 0x13, 0x14d181d, 0x4, 0xc000066f18, 0x3, 0x3, 0xc000030400, 0x142aa80, ...)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc0000b64e0, 0xc0000b4578, 0x13, 0xc0001b4718, 0x3, 0x3, 0x14a1660, 0x14b1601, 0xc000030780)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc0000ab880, 0xc00014e000, 0xc0000263a0, 0xc0000263b0, 0xc0000ce280, 0xc00000c220, 0x1416900, 0xc00014c680, 0x16, 0x14168c0, ...)
	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:481 +0x47e
2018/09/13 01:06:45 Got autocompletion request for '/Users/bernardo/dev/golang/src/github.com/berfarah/knoch/main.go'
2018/09/13 01:06:45 Cursor at: 97
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
runtime/debug.Stack(0xb, 0xc000065828, 0x1)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc0001f85a0)
	/Users/bernardo/dev/golang/src/github.com/mdempsky/gocode/server.go:72 +0x94
panic(0x1453d00, 0x184fd80)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
main.(*Server).AutoComplete(0x187f628, 0xc00012f110, 0xc0001f85a0, 0x0, 0x0)
	/Users/bernardo/dev/golang/src/github.com/mdempsky/gocode/server.go:84 +0x9d9
reflect.Value.call(0xc0000b64e0, 0xc0000b4578, 0x13, 0x14d181d, 0x4, 0xc000065f18, 0x3, 0x3, 0xc0000aba40, 0x142aa80, ...)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc0000b64e0, 0xc0000b4578, 0x13, 0xc00004f718, 0x3, 0x3, 0x14a1660, 0x14b1601, 0xc0001e2440)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc0000ab880, 0xc00014e000, 0xc000026368, 0xc000026380, 0xc0000ce280, 0xc0000bade0, 0x1416900, 0xc00012f110, 0x16, 0x14168c0, ...)
	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.11/libexec/src/net/rpc/server.go:481 +0x47e

```

**Comment by berfarah** [comment]
@bhcleek Thanks for fixing this! I've validated against the newer neovim versions and it works 😄 (worth noting that 0.2 was broken, but a simple `brew upgrade neovim` was enough to get this working)

**Comment by bhcleek** [comment]
Thank you for the confirmation!

I think some of the details of how channels work in Neovim was changed between 0.2 and 0.3;  vim-go will not be able to maintain backward compatibility with all pre-1.0 releases of Neovim.
