### ISSUE TITLE
vim-go triggering textDocument/* on non-existent files

### ISSUE THREAD

**Issue by minight** [fatih/vim-go#2786]
### What did you do? (required: The issue will be **closed** when not provided)

vim-go triggers `textDocument/definition` and `textDocument/references` on non-existent files causing gopls to panic and crash when attempting to resolve references.

**Reproduction**
1. Using the following vim config
2. navigate to a new directory e.g. /tmp/vimtest
3. open vim on a new non-existent-file. `vim -u config.vim test.go`
4. Observe gopls crash 

This error has also been observed to occur when opening existing go files, but rapidly switching to another buffer that is temporary/non-existent, e.g. NERDTree split.

This can be observed by 
1. Open an existing go file
2. Open nerdtree with `:NERDTreeFind`
3. Observe gopls crash. If it does not crash, `^W^L` to the .go split, and run `:NERDTreeFind` again.

### What did you expect to happen?
gopls not to crash and vim-go not to run the textDocument/references on a non-existent file.

### What happened instead?
gopls panics and crashes, resulting in the channel closing and all subsequent hover operations to fail

```
===== sent =====
Content-Length: 456

{"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"rootUri": "file:///tmp/vimtest", "capabilities": {"workspace": {"workspaceFolders": true, "configuration": true, "didChangeConfiguration": {"dynamicRegistration": true}}, "textDocument": {"completion": {"completionItem": {"snippetSupport": false}}, "hover": {"contentFormat": ["plaintext"]}}}, "processId": 32523, "workspaceFolders": [{"uri": "file:///tmp/vimtest", "name": "/tmp/vimtest"}]}}
===== stderr =====
2020/03/25 17:30:38 debug server listening on port 33561
===== received =====
Content-Length: 870

{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["tidy","upgrade.dependency"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":""}},"id":1}
===== sent =====
Content-Length: 57

{"method": "initialized", "jsonrpc": "2.0", "params": {}}
===== sent =====
Content-Length: 173

{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 2, "params": {"textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
===== sent =====
Content-Length: 214

{"method": "textDocument/references", "jsonrpc": "2.0", "id": 3, "params": {"context": {"includeDeclaration": true}, "textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
===== received =====
Content-Length: 268

{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]},"id":1}
===== sent =====
Content-Length: 43

{"id": 1, "jsonrpc": "2.0", "result": null}
===== received =====
Content-Length: 199

{"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///tmp/vimtest","section":"gopls"},{"scopeUri":"file:///tmp/vimtest","section":"gopls-/tmp/vimtest"}]},"id":2}
===== sent =====
Content-Length: 143

{"id": 2, "jsonrpc": "2.0", "result": [{"buildFlags": [], "hoverKind": "NoDocumentation"}, {"buildFlags": [], "hoverKind": "NoDocumentation"}]}
===== received =====
Content-Length: 1887

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/03/25 17:30:38 Build info\n----------\ngolang.org/x/tools/gopls v0.3.4\n    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/sergi/go-diff@v1.0.0 h1:Kpca3qRNrduNnOQeazBd0ysaKrUJiIuISHxogkT9RPQ=\n    golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee h1:WG0RUwxtNT4qqaXX3DPA8zHFNm/D9xaBpxzHt1WcA/E=\n    golang.org/x/sync@v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=\n    golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a h1:hKrQy/q8/Xivoqgw6nGiz1jqpn1WGBLDcWLZwW0983E=\n    golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898 h1:/atklqdjdhuosWIl6AIbOeHJjicWYPqR9bpxqxYG2pA=\n    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=\n    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=\n\nGo info\n-------\ngo version go1.14 linux/amd64\n\nGO111MODULE=\"\"\nGOARCH=\"amd64\"\nGOBIN=\"\"\nGOCACHE=\"/home/sean/.cache/go-build\"\nGOENV=\"/home/sean/.config/go/env\"\nGOEXE=\"\"\nGOFLAGS=\"\"\nGOHOSTARCH=\"amd64\"\nGOHOSTOS=\"linux\"\nGOINSECURE=\"\"\nGONOPROXY=\"\"\nGONOSUMDB=\"\"\nGOOS=\"linux\"\nGOPATH=\"/home/sean/.go\"\nGOPRIVATE=\"\"\nGOPROXY=\"https://proxy.golang.org,direct\"\nGOROOT=\"/usr/local/go\"\nGOSUMDB=\"sum.golang.org\"\nGOTMPDIR=\"\"\nGOTOOLDIR=\"/usr/local/go/pkg/tool/linux_amd64\"\nGCCGO=\"gccgo\"\nAR=\"ar\"\nCC=\"gcc\"\nCXX=\"g++\"\nCGO_ENABLED=\"1\"\nGOMOD=\"\"\nCGO_CFLAGS=\"-g -O2\"\nCGO_CPPFLAGS=\"\"\nCGO_CXXFLAGS=\"-g -O2\"\nCGO_FFLAGS=\"-g -O2\"\nCGO_LDFLAGS=\"-g -O2\"\nPKG_CONFIG=\"pkg-config\"\nGOGCCFLAGS=\"-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build682235652=/tmp/go-build -gno-record-gcc-switches\"\n"}}
===== received =====
Content-Length: 171

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/03/25 17:30:39 go/packages.Load\n\tsnapshot = 0\n\tquery = [./ builtin]\n\tpackages = 2"}}
===== received =====
Content-Length: 163

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/03/25 17:30:39 go/packages.Load\n\tsnapshot = 0\n\tquery = [./]\n\tpackages = 1"}}
===== received =====
Content-Length: 114

{"jsonrpc":"2.0","error":{"code":0,"message":"getting file for Identifier: no PackageHandles","data":null},"id":2}
===== received =====
Content-Length: 186

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/03/25 17:30:39 go/packages.Load\n\tsnapshot = 0\n\tquery = [file=/tmp/vimtest/test.go]\n\tpackages = 0"}}
===== received =====
Content-Length: 186

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/03/25 17:30:39 go/packages.Load\n\tsnapshot = 0\n\tquery = [file=/tmp/vimtest/test.go]\n\tpackages = 0"}}
===== received =====
Content-Length: 121

{"jsonrpc":"2.0","error":{"code":-32603,"message":"method \"textDocument/references\" did not reply","data":null},"id":3}
===== stderr =====
panic: runtime error: index out of range [0] with length 0
===== stderr =====
===== stderr =====
goroutine 80 [running]:
===== stderr =====
golang.org/x/tools/internal/lsp/source.References(0xe12e60, 0xc0003c2360, 0xe24f00, 0xc0003d0060, 0xe114e0, 0xc0002876c0, 0x4018000000000000, 0x3ff0000000000000, 0xc000208001, 0x0, ...)
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/source/references.go:38 +0x1191
===== stderr =====
golang.org/x/tools/internal/lsp.(*Server).references(0xc000220e00, 0xe12e60, 0xc000423c80, 0xc0002246e0, 0xc0002246e0, 0x0, 0x0, 0x0, 0xc0001926e0)
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/references.go:19 +0xe7
===== stderr =====
golang.org/x/tools/internal/lsp.(*Server).References(0xc000220e00, 0xe12e60, 0xc000423c80, 0xc0002246e0, 0xc0002246e0, 0x0, 0x0, 0x0, 0x0)
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/server_gen.go:148 +0x4d
===== stderr =====
golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0xe2d340, 0xc000220e00, 0xe12e60, 0xc000423c80, 0xc000425080, 0xc000047400, 0xc000210000)
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/lsp/protocol/tsserver.go:400 +0x2692
===== stderr =====
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc00021d260, 0xc000425080, 0xc000421200, 0xe12e60, 0xc000423c80, 0x0, 0x0, 0xc00027f6e0)
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/jsonrpc2/jsonrpc2.go:372 +0x160
===== stderr =====
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
===== stderr =====
	/home/sean/.go/pkg/mod/golang.org/x/tools@v0.0.0-20200316194252-fafb6e2e8a4a/internal/jsonrpc2/jsonrpc2.go:356 +0x850
===== sent =====
Content-Length: 173

{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 4, "params": {"textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
===== sent =====
Content-Length: 214

{"method": "textDocument/references", "jsonrpc": "2.0", "id": 5, "params": {"context": {"includeDeclaration": true}, "textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
===== sent =====
Content-Length: 173

{"method": "textDocument/definition", "jsonrpc": "2.0", "id": 6, "params": {"textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
===== sent =====
Content-Length: 214

{"method": "textDocument/references", "jsonrpc": "2.0", "id": 7, "params": {"context": {"includeDeclaration": true}, "textDocument": {"uri": "file:///tmp/vimtest/test.go"}, "position": {"character": 1, "line": 6}}}
erations to fail.

```

subsequent hovers over go files result in 
```
Error detected while processing function <SNR>195_handler[2]..go#tool#Info[9]..go#lsp#Info[17]..198[47]..201:
line   11:
E900: Invalid channel id
Error detected while processing function <SNR>195_handler[5]..go#guru#SameIds[15]..go#lsp#SameIDs[14]..198[47]..201:
line   11:
E900: Invalid channel id
Error detected while processing function <SNR>195_handler[2]..go#tool#Info[9]..go#lsp#Info[17]..198[47]..201:
line   11:
E900: Invalid channel id
Error detected while processing function <SNR>195_handler[5]..go#guru#SameIds[15]..go#lsp#SameIDs[14]..198[47]..201:
line   11:
E900: Invalid channel id
```

#### vim-go version:
master @ f2e1f9827a659188ef3e203d65edffe6448c9074

####  `vimrc` you used to reproduce:
```vim
" vim-plug autoconfig if not already installed
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | nested source $MYVIMRC
endif

call plug#begin('~/.config/nvim/bundle')
    Plug 'preservim/nerdtree'
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

" vim-go {
    let g:go_def_mode='gopls'
    let g:go_info_mode='gopls'
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_types = 1
    let g:go_auto_sameids = 1
    let g:go_auto_type_info = 1

    let g:go_debug=["lsp"]
" }

let mapleader = "\<Space>"
" nerdtree {
    nnoremap <leader>f :NERDTreeFind<CR>
    nnoremap <leader>n :NERDTreeToggle<CR>
" }

" Mappings {
    set mouse=a
    if !has('nvim') && exists('$TMUX')  " Support resizing in tmux
        set ttymouse=xterm2
    endif
" }
```

<details><summary>vimrc</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):

NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3

#### Go version (`go version`):

go version go1.14 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sean/.cache/go-build"
GOENV="/home/sean/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sean/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build410852890=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.3.4
    golang.org/x/tools/gopls@v0.3.4 h1:4GC7q/pXQ/tsxHBGVdsMdlB4gCxVC06m/7rIXg1Px4E=

</pre></details>

#### vim-go configuration:
<details><summary>vim-go configuration</summary><br><pre>
g:go_auto_type_info = 1
g:go_highlight_extra_types = 1
g:go_highlight_operators = 1
g:go_highlight_fields = 1
g:go_debug = ['lsp']
g:go_def_mode = 'gopls'
g:go_info_mode = 'gopls'
g:go_auto_sameids = 1
g:go_highlight_structs = 1
g:go_highlight_functions = 1
g:go_gotags_bin = 'gotags'
g:go_highlight_types = 1
g:go_jump_to_error = 1
g:go_highlight_methods = 1
g:go_loaded_gosnippets = 1
g:go_highlight_build_constraints = 1
g:go_loaded_install = 1
</pre></details>

#### filetype detection configuration:
<details><summary>filetype detection</summary><br><pre>
filetype detection:ON  plugin:ON  indent:ON
</pre></details>

**Comment by stamblerre** [comment]
I don't think that this will fix the problem, but I just mailed https://golang.org/cl/225523 to handle the nil pointer. In general, `gopls` should handle files that don't exist on disk as long as the editor sends `gopls` a `textDocument/didOpen` notification.

**Comment by minight** [comment]
Running on gopls@5d86d385bf88f37d685892cf7b0bcdbe84b10c1e (tip of master as of writing), issue seems to be resolved when attempting the first testcase (non-exist go file) and seems to be resolved when browsing code generally. Closing unless I notice a regression.

thanks!

**Comment by bhcleek** [comment]
I can modify vim-go to handle that nil, too.

**Comment by bhcleek** [comment]
I misread this. I don't think there's anything for vim-go to do here.

vim-go _does_ send `didOpen` on all files AFAIK, and then error here doesn't seem to be in vim-go's handling of the response from gopls.
