### ISSUE TITLE
FillStruct error: runtime error

### ISSUE THREAD

**Issue by ftamhar** [fatih/vim-go#3338]
### What did you do? (required: The issue will be **closed** when not provided)
I want to learn [redis](https://github.com/go-redis/redis) and when I try the quickstart I got an error
My code :
```go
rdb := redis.NewClient(&redis.Option[s]{})
```
**pointer is on 's'**

I run :
```shell
:GoFillStruct
```

### What did you expect to happen?
It's from goland
```go
rdb := redis.NewClient(&redis.Options{
		Network:            "",
		Addr:               "",
		Dialer:             nil,
		OnConnect:          nil,
		Username:           "",
		Password:           "",
		DB:                 0,
		MaxRetries:         0,
		MinRetryBackoff:    0,
		MaxRetryBackoff:    0,
		DialTimeout:        0,
		ReadTimeout:        0,
		WriteTimeout:       0,
		PoolFIFO:           false,
		PoolSize:           0,
		MinIdleConns:       0,
		MaxConnAge:         0,
		PoolTimeout:        0,
		IdleTimeout:        0,
		IdleCheckFrequency: 0,
		TLSConfig:          nil,
		Limiter:            nil,
	})
```
### What happened instead?
error
```shell
vim-go: panic: runtime error: invalid memory address or nil pointer dereference
vim-go: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11d9da5]
vim-go:
vim-go: goroutine 1 [running]:
vim-go: go/token.(*File).Name(...)
vim-go:         /usr/local/go/src/go/token/position.go:113
vim-go: main.findPos({0xc01a8b1d38, 0x1, 0x0}, {0xc0001220c0, 0x29}, 0xb1)
vim-go:         /Users/rahmat/go/pkg/mod/github.com/davidrjenni/reftools@v0.0.0-20
210213085015-40322ffdc2e4/cmd/fillstruct/main.go:191 +0x165
vim-go: main.byOffset({0xc01a8b1d38, 0x0, 0x0}, {0xc0001220c0, 0x4}, 0x123831b)
vim-go:         /Users/rahmat/go/pkg/mod/github.com/davidrjenni/reftools@v0.0.0-20
210213085015-40322ffdc2e4/cmd/fillstruct/main.go:166 +0x45
vim-go: main.main()
vim-go:         /Users/rahmat/go/pkg/mod/github.com/davidrjenni/reftools@v0.0.0-20
210213085015-40322ffdc2e4/cmd/fillstruct/main.go:133 +0x531
```
#### vim-go version:
v1.25

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary>

```vim
filetype plugin indent on

set autowrite

" Go syntax highlighting
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_variable_declarations = 1

" Auto formatting and importing
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"

" Status line types/signatures
let g:go_auto_type_info = 1

" Run :GoBuild or :GoTestCompile based on the go file
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#test#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
```
</details>

#### Vim version (first three lines from `:version`):

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

#### Go version (`go version`):
go version go1.17.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rahmat/Library/Caches/go-build"
GOENV="/Users/rahmat/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rahmat/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rahmat/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/l3/91lvg31x3h966wk6_5fbwxj00000gn/T/go-build3429250172=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output:</summary><br><pre>

golang.org/x/tools/gopls v0.7.4
    golang.org/x/tools/gopls@v0.7.4 h1:hw8cpqjio1iMwIKbbDkG3MeW4l8R9dY/yqOHqv7HImA=
</pre></details>

**Comment by ftamhar** [comment]
fix, I use **gopls** to **:GoFillStruct**
