### ISSUE TITLE
Go 1.18.3  internal error: rs.graph is unexpectedly nil with -mod=vendor

### ISSUE THREAD

**Issue by peterwillcn** [fatih/vim-go#3429]
key 'g+d'
```
vim-go: [definition] FAIL
vim-go: err: exit status 2: stderr: panic: internal error: rs.graph is unexpectedly nil with -mod=vendor
vim-go:
vim-go: goroutine 1 [running]:
vim-go: cmd/go/internal/modload.updatePrunedRoots({0x16dca98, 0xc000024220}, 0x100f6db?, 0xc000090230, {0xc0000100b0, 0x1, 0x0?}, {0x0, 0x0, 0x0}, ...)
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/modload/buildlist.go:955 +0xb6f
vim-go: cmd/go/internal/modload.updateRoots({0x16dca98?, 0xc000024220?}, 0x100e765?, 0x0?, {0xc0000100b0?, 0x0?, 0xc0000d67b0?}, {0x0, 0x0, 0x0}, ...)
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/modload/buildlist.go:653 +0xb7
vim-go: cmd/go/internal/modload.(*loader).updateRequirements(0xc0001b8410, {0x16dca98, 0xc000024220})
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/modload/load.go:1367 +0x2a5
vim-go: cmd/go/internal/modload.loadFromRoots({0x16dca98, 0xc000024220}, {{{0x0, 0x0}, 0xc0001b23c0, 0x0, {0x0, 0x0}, 0x0, 0x1, ...}, ...})
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/modload/load.go:1102 +0x70f
vim-go: cmd/go/internal/modload.LoadPackages({0x16dca98?, 0xc000024220}, {{0x0, 0x0}, 0xc0001b23c0, 0x0, {0x0, 0x0}, 0x0, 0x1, ...}, ...)
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/modload/load.go:343 +0x308
vim-go: cmd/go/internal/load.PackagesAndErrors({0x16dca98?, 0xc000024220?}, {0x27?, 0x0?, 0x0?, 0x0?}, {0xc0000201d0, 0x1, 0x1})
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/load/pkg.go:2719 +0x1cb
vim-go: cmd/go/internal/list.runList({0x16dca98?, 0xc000024220}, 0xc00002c438?, {0xc0000201d0?, 0x1, 0x1})
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/internal/list/list.go:508 +0x9fa
vim-go: main.invoke(0x19bf160, {0xc000020190, 0x5, 0x5})
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/main.go:218 +0x2ee
vim-go: main.main()
vim-go:         /usr/local/Cellar/go/1.18.3/libexec/src/cmd/go/main.go:175 +0x78e
vim-go: : packages.Load error
```
![Screen Shot 2022-06-26 at 19 12 43](https://user-images.githubusercontent.com/323794/175811441-29b56d0e-90ef-4df9-9d0a-f13b85e4c0d5.png)

**Comment by bhcleek** [comment]
There isn't enough information here for me to know how to duplicate this issue. How is your source code and module structured? Can you provide a simple reproduction case?

Though there isn't enough for me to know exactly what's wrong, it looks like this is an expected outcome in some configurations: https://go.dev/src/cmd/go/internal/modload/buildlist.go#L955. I suspect the problem here is when vim-go tries to run `go list` from within the directory that contains the file for the active buffer. You can confirm that for yourself by going to that directory at the command line and running `go list`.

**Comment by peterwillcn** [comment]
When the mouse is placed over a word, syncing the same word is highlighted and an error is reported
vim version
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```
vim config for vim-go
```
au FileType go nmap <F8> :GoMetaLinter<cr>
au FileType go nmap <F9> :GoCoverageToggle -short<cr>
au FileType go nmap <F10> :GoTest -short<cr>
au FileType go nmap <F12> <Plug>(go-def)
au Filetype go nmap <leader>ga <Plug>(go-alternate-edit)
au Filetype go nmap <leader>gah <Plug>(go-alternate-split)
au Filetype go nmap <leader>gav <Plug>(go-alternate-vertical)
au FileType go nmap <leader>gt :GoDeclsDir<cr>
au FileType go nmap <leader>gc <Plug>(go-coverage-toggle)
au FileType go nmap <leader>gd <Plug>(go-def)
au FileType go nmap <leader>gdv <Plug>(go-def-vertical)
au FileType go nmap <leader>gdh <Plug>(go-def-split)
au FileType go nmap <leader>gD <Plug>(go-doc)
au FileType go nmap <leader>gDv <Plug>(go-doc-vertical)
```

**Comment by bhcleek** [comment]
I suspect this doesn't happen in all modules. I'd need to know a basic code structure for how to duplicate this if you want me to try to help you understand what's going on.

Did you try my suggestion to duplicate with `go list` at the commandline?
